### ISSUE TITLE
/explorerでダミーデータでなく実際のデータを表示させる

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/anke-to-UI#144]
`onMount`時にpagesの中でapiを叩いてデータを持ってくるように
そのデータをpropsでcomponentsに渡してダミーデータを置き換える
`onMount`についてはvueのライフサイクルを参照

#143 解決後にやる

**Comment by kohbanye** [comment]
[ここ](https://github.com/traPtitech/anke-to-UI/blob/master/src/pages/Explorer.vue#L32)みたいにgetQuestionnairesするとChromeで
```
Access to XMLHttpRequest at 'https://q.trap.jp/login?redirect=https://anke-to-dev.trapti.tech/api/questionnaires?sort=modified_at&page=1&nontargeted=false' (redirected from 'http://localhost:3001/api/questionnaires?sort=modified_at&page=1&nontargeted=false') from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
と出てきて詰まってます。Access-Control-Allow-Originをサーバー側で設定してもらう必要があるってことですか？

**Comment by ryoha000** [comment]
僕の手元じゃ出てないんで純粋に叩けてないのかなって思います
言ってなかった気もするんで叩くのに必要な手順をtraQで共有します:pray:
