### ISSUE TITLE
/targetedでダミーデータでなく実際のデータを表示させる

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/anke-to-UI#145]
`onMount`時にpagesの中でapiを叩いてデータを持ってくるように
そのデータをpropsでcomponentsに渡してダミーデータを置き換える
`onMount`についてはvueのライフサイクルを参照

**Comment by tantakaa** [comment]
`/@/components/UI/CardContentDetail.vue` でpropsを用いてデータを受け取る形で問題ないですか？

**Comment by ryoha000** [comment]
それで良いです👍

**Comment by tantakaa** [comment]
#351
