### ISSUE TITLE
/explorerのフィルター部分のロジック

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/anke-to-UI#147]
とりあえず各ソートに型をつける
この辺を参考にenumっぽく
https://www.kabuku.co.jp/developers/good-bye-typescript-enum

そしたらアンケートの配列からそれぞれをソート/フィルターする関数を書く

**Comment by ryoha000** [comment]
あと外の部分をクリックしたら閉じるようにする

**Comment by kohbanye** [comment]
`getQuestionnaires`はすでにソートされた配列を返してくれてますが、クライアント側でソート/フィルターしたほうがいいですか？

**Comment by ryoha000** [comment]
返信忘れてた。
ごめん
ソートって言うのは`createdAt`だけじゃなくてこの画像部分で出来るソートって意味だった:pray:
![image](https://user-images.githubusercontent.com/48485650/108873934-ff682f80-763e-11eb-8e51-bdf5299cb61c.png)
