### ISSUE TITLE
サイドバーのレスポンシブ対応

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/anke-to-UI#149]
旧anke-toと同じような仕様に
出す出さないが変わったタイミングでアニメーションはあってもいいかもしれんがそれは別のissueで

**Comment by annin3** [comment]
旧anke-toにある`client/src/style/global.scss`みたいなの作っても大丈夫でしょうか？

**Comment by ryoha000** [comment]
どういう意図で？

**Comment by ryoha000** [comment]
メディアクエリ書かなくてもmax-widthとかで各コンポーネントごとに設定すればいいかなと思ってた

**Comment by annin3** [comment]
特に深い意図はないです。。。
直接やります
